# Test stable, lts, and 11.x
language: node_js

node_js:
  - node
  - lts/*
  - 11
  - 8

os:
  - osx
  - windows
  - linux
  - windows

jobs:
  allow_failures:
    - node_js: 8

dist: focal

install: |
  if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    powershell -ExecutionPolicy Bypass -File "$TRAVIS_BUILD_DIR/ci/setup/setup-win.ps1";
  fi

script: |
  if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then
    . $TRAVIS_BUILD_DIR/ci/tests/examples-linux.sh;
  elif [ "$TRAVIS_OS_NAME" = "windows" ]; then
    powershell -ExecutionPolicy Bypass -File "$TRAVIS_BUILD_DIR/ci/tests/examples-win.ps1";
  fi
  return $?
